maze_type: edge_grid_3d
config:
  cell_elements:
    - name: open
      token: '.'
    - name: wall
      token: '#'
    - name: elevator
      token: 'E'
    - name: escalator
      token: 'S'
  wall_elements:
    - name: wall
      token: '#'
    - name: open
      token: '-'
layout:
  levels:
    - id: ground
      layout:
        cells: |
          E S
          . .
        walls:
          vertical: |
            # # #
            # # #
          horizontal: |
            # #
            # #
            # #
    - id: upper
      layout:
        cells: |
          E .
          S .
        walls:
          vertical: |
            # # #
            # # #
          horizontal: |
            # #
            # #
            # #
  connectors:
    - type: elevator
      from: {level: ground, row: 0, col: 0}
      to: {level: upper, row: 0, col: 0}
    - type: escalator
      from: {level: ground, row: 0, col: 1}
      to: {level: upper, row: 1, col: 0}
