maze_type: occupancy_grid
config:
  cell_elements:
    - name: open
      token: "."
      value: 0
  wall_elements:
    - name: wall
      token: "#"
      value: 1
layout:
  grid: |
    #######
    #..#..#
    #.....#
    #######
