maze_type: occupancy_grid
config:
  cell_elements:
    - name: wall
      token: "#"
      value: 1
    - name: open
      token: "."
      value: 0
    - name: button
      token: "B"
      value: 2
layout:
  grid:
    - "#####"
    - "#.B.#"
    - "#...#"
    - "#####"
