maze_type: occupancy_grid
config:
  cell_elements:
  - name: open
    token: '.'
    value: 0
  - name: start
    token: 'S'
    value: 2
  - name: goal
    token: 'G'
    value: 3
  wall_elements:
  - name: wall
    token: '#'
    value: 1
  - name: wall_1
    token: '1'
    value: 4
  - name: wall_2
    token: '2'
    value: 5
layout:
  grid: |
    ___ 0 1 2 3 4 5 6 7
    0 | # S # # # 2 # #
    1 | # . # . . . . G
    2 | # . # . . # # #
    3 | # . # 2 . . . #
    4 | # . 2 . . # . #
    5 | 1 . . . . . . #
    6 | # . # . . # . #
    7 | # # # # # # # #
