maze_type: radial_arm
config:
  cell_elements:
  - name: open
    token: '.'
    value: 0
  wall_elements:
  - name: wall
    token: '#'
    value: 1
  - name: open
    token: '-'
    value: 0
layout:
  center_hub:
    shape: circular
    angle_degrees: 180.0
    radius: 2.0
  arms:
  - layout:
      cells: |
        ___ 0 1 2 3
        0 | . . . .
      walls:
        vertical: |
          ___ 0 1 2 3 4
          0 | - - - - #
        horizontal: |
          ___ 0 1 2 3
          0 | # # # #
          1 | # # # #
  - layout:
      cells: |
        ___ 0 1 2 3
        0 | . . . .
      walls:
        vertical: |
          ___ 0 1 2 3 4
          0 | - - - - #
        horizontal: |
          ___ 0 1 2 3
          0 | # # # #
          1 | # # # #
  - layout:
      cells: |
        ___ 0 1 2 3
        0 | . . . .
      walls:
        vertical: |
          ___ 0 1 2 3 4
          0 | - - - - #
        horizontal: |
          ___ 0 1 2 3
          0 | # # # #
          1 | # # # #
  - layout:
      cells: |
        ___ 0 1 2 3
        0 | . . . .
      walls:
        vertical: |
          ___ 0 1 2 3 4
          0 | - - - - #
        horizontal: |
          ___ 0 1 2 3
          0 | # # # #
          1 | # # # #
  - layout:
      cells: |
        ___ 0 1 2 3
        0 | . . . .
      walls:
        vertical: |
          ___ 0 1 2 3 4
          0 | - - - - #
        horizontal: |
          ___ 0 1 2 3
          0 | # # # #
          1 | # # # #
